// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayingSystem;

namespace PayingSystem.Migrations
{
    [DbContext(typeof(PayingSystemDataBaseContext))]
    partial class PayingSystemDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PayingSystem.Account", b =>
                {
                    b.Property<int>("CardNumber");

                    b.Property<double>("Balance");

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("Expire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate()+(5))");

                    b.Property<string>("HashPassword");

                    b.HasKey("CardNumber")
                        .HasName("PK__Accounts__A4E9FFE84A9473EA");

                    b.HasIndex("ClientId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("PayingSystem.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("Flat");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnName("HOUSE")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("PayingSystem.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.HasKey("ClientId")
                        .HasName("PK__tmp_ms_x__E67E1A24DE1A5C39");

                    b.HasIndex("AddressId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("PayingSystem.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Price");

                    b.Property<int>("ProductListId");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("ProductId")
                        .HasName("PK__tmp_ms_x__B40CC6CDA5D2A16C");

                    b.HasIndex("ProductListId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("PayingSystem.ProductList", b =>
                {
                    b.Property<int>("ProductListId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("ProductListId")
                        .HasName("PK__tmp_ms_x__86F3FF2598A9B94C");

                    b.HasIndex("ShopName", "AddressId");

                    b.ToTable("ProductList");
                });

            modelBuilder.Entity("PayingSystem.Shop", b =>
                {
                    b.Property<string>("ShopName")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int>("AddressId");

                    b.Property<int>("CardNumber");

                    b.HasKey("ShopName", "AddressId")
                        .HasName("PK__Shops__C40BBF388095871C");

                    b.HasIndex("AddressId");

                    b.HasIndex("CardNumber");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("PayingSystem.Account", b =>
                {
                    b.HasOne("PayingSystem.Client", "Client")
                        .WithMany("Account")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK__Accounts__Client__5DCAEF64");
                });

            modelBuilder.Entity("PayingSystem.Client", b =>
                {
                    b.HasOne("PayingSystem.Address", "Address")
                        .WithMany("Clients")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK__Clients__Address__6477ECF3");
                });

            modelBuilder.Entity("PayingSystem.Product", b =>
                {
                    b.HasOne("PayingSystem.ProductList", "ProductList")
                        .WithMany("Products")
                        .HasForeignKey("ProductListId")
                        .HasConstraintName("FK__Products__Produc__68487DD7");
                });

            modelBuilder.Entity("PayingSystem.ProductList", b =>
                {
                    b.HasOne("PayingSystem.Shop", "Shops")
                        .WithMany("ProductLists")
                        .HasForeignKey("ShopName", "AddressId")
                        .HasConstraintName("FK__ProductLists__60A75C0F");
                });

            modelBuilder.Entity("PayingSystem.Shop", b =>
                {
                    b.HasOne("PayingSystem.Address", "Address")
                        .WithMany("Shops")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK__Shops__AddressId__656C112C");

                    b.HasOne("PayingSystem.Account", "Account")
                        .WithMany("Shops")
                        .HasForeignKey("CardNumber")
                        .HasConstraintName("FK__Shops__CardNumbe__300424B4");
                });
#pragma warning restore 612, 618
        }
    }
}
